// external declaration of sound table:

extern far cdata SNDTBL_SOUND_TABLE;

// external declarations of addresses of sounds for direct access:

extern far cdata SX_Blinds_closing;
extern far cdata SX_Blinds_opening;
extern far cdata SX_Doors_opening;
extern far cdata SX_Entering_Sleeping_Mode;
extern far cdata SX_Error__please_try_again;
extern far cdata SX_Listening;
extern far cdata SX_Error;
extern far cdata SX_Time_out;
extern far cdata SX_Low_battery;
extern far cdata SX_Power_on;
extern far cdata SX_Do_you_want_to_perform_another_task;
extern far cdata SX_low_battery__please_get_a_new_replacement;
extern far cdata SX_Battery_percentage_good;
extern far cdata SX_Say_the_trigger_command;
extern far cdata SX_Say_a_command_in_group_1;
extern far cdata SX_Please_stop_the_blind_after_the_beep;
extern far cdata SX_The_blind_has_stopped;

// constants defining sounds as entries in the sound table:

#define SND_Blinds_closing      1
#define SND_Blinds_opening      2
#define SND_Doors_opening       3
#define SND_Entering_Sleeping_Mode 4
#define SND_Error__please_try_again 5
#define SND_Listening           6
#define SND_Error               7
#define SND_Time_out            8
#define SND_Low_battery         9
#define SND_Power_on            10
#define SND_Do_you_want_to_perform_another_task 11
#define SND_low_battery__please_get_a_new_replacement 12
#define SND_Battery_percentage_good 13
#define SND_Say_the_trigger_command 14
#define SND_Say_a_command_in_group_1 15
#define SND_Please_stop_the_blind_after_the_beep 16
#define SND_The_blind_has_stopped 17

